# Generated by Django 5.1.10 on 2025-08-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_export", "0010_alter_convertedformat_export_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="annotation_filter_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="export",
            name="serialization_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="export",
            name="task_filter_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="convertedformat",
            name="file",
            field=models.FileField(null=True, upload_to="D:\\rail_user_data"),
        ),
        migrations.AlterField(
            model_name="export",
            name="file",
            field=models.FileField(null=True, upload_to="D:\\rail_user_data"),
        ),
    ]
