# Generated by Django 5.1.10 on 2025-08-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0007_organizationmember_role"),
        ("users", "0011_user_custom_hotkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authorization",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration for the dataset",
                verbose_name="authorization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration for the dataset",
                verbose_name="user name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_token",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration for the dataset",
                verbose_name="user token",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["authorization"], name="htx_user_authori_9deea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_token"], name="htx_user_user_to_f6804b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_name"], name="htx_user_user_na_812d21_idx"
            ),
        ),
    ]
