# Generated by Django 5.1.10 on 2025-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_authorization_user_user_name_user_user_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="authorization",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of associated dataset",
                max_length=100,
                verbose_name="authorization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of associated dataset",
                max_length=100,
                verbose_name="user name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of associated dataset",
                max_length=100,
                verbose_name="user token",
            ),
        ),
    ]
