# Generated by Django 5.1.10 on 2025-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_authorization_alter_user_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="authorization",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of associated dataset",
                max_length=300,
                verbose_name="authorization",
            ),
        ),
    ]
